#!/usr/bin/env python3
"""
Step 1: Render/OCR Maths RSAggarwal PDF and build chapter/page extraction JSON.

This version reads chapter metadata generated by make_maths_rsaggarwal_step_0.py
from output/maths_rsagarwal/Maths_RSAgarwal_chapters.json instead of using a static CHAPTERS array.
"""

import json
import os
import re
import subprocess
import tempfile
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import fitz  # PyMuPDF

# Expected location when this file is placed at:
#   <project_root>/app/maths_rsaggarwal/make_maths_rsaggarwal_step_1.py
# You can override any path with the environment variables below.
PROJECT_ROOT = Path(os.environ.get(
    'MATHS_RSAGGARWAL_ROOT',
    Path(__file__).resolve().parents[2],
))

PDF_PATH = Path(os.environ.get(
    'MATHS_RSAGGARWAL_PDF',
    PROJECT_ROOT / 'input' / 'Maths_RSAgarwal.pdf',
))

OUTPUT_DIR = Path(os.environ.get(
    'MATHS_RSAGGARWAL_OUTPUT_DIR',
    PROJECT_ROOT / 'output' / 'maths_rsagarwal',
))

OUTPUT_JSON = OUTPUT_DIR / 'Maths_RSAgarwal_math_aware_extraction.json'
VALIDATION_REPORT = OUTPUT_DIR / 'Maths_RSAgarwal_math_aware_validation_report.txt'
OCR_CACHE_DIR = OUTPUT_DIR / '.ocr_cache' / 'maths_rsaggarwal_ocr_cache_fast'
HIGH_RES_OCR_CACHE_DIR = OUTPUT_DIR / '.ocr_cache' / 'maths_rsaggarwal_ocr_cache'

# In this PDF, printed page 1 maps to PDF page 8.
PRINTED_OFFSET = 7
RENDER_SCALE = 1.2  # 72 * 2.5 = 180 DPI. Good balance for this scanned PDF.
TESSERACT_LANG = 'eng'
TESSERACT_PSM = '4'  # block/paragraph segmentation preserves equations better than selectable text layer
MAX_WORKERS = int(os.environ.get('MATH_OCR_WORKERS', '6'))

# CHAPTERS = [
#     {"chapter_number":"1", "chapter_title":"Integers", "printed_start_page":1},
#     {"chapter_number":"2", "chapter_title":"Fractions", "printed_start_page":16},
#     {"chapter_number":"3", "chapter_title":"Decimals", "printed_start_page":36},
#     {"chapter_number":"4", "chapter_title":"Rational Numbers", "printed_start_page":54},
#     {"chapter_number":"5", "chapter_title":"Exponents", "printed_start_page":84},
#     {"chapter_number":"6", "chapter_title":"Algebraic Expressions", "printed_start_page":97},
#     {"chapter_number":"7", "chapter_title":"Linear Equations in One Variable", "printed_start_page":107},
#     {"chapter_number":"8", "chapter_title":"Ratio and Proportion", "printed_start_page":119},
#     {"chapter_number":"9", "chapter_title":"Unitary Method", "printed_start_page":132},
#     {"chapter_number":"10", "chapter_title":"Percentage", "printed_start_page":138},
#     {"chapter_number":"11", "chapter_title":"Profit and Loss", "printed_start_page":152},
#     {"chapter_number":"12", "chapter_title":"Simple Interest", "printed_start_page":161},
#     {"chapter_number":"13", "chapter_title":"Lines and Angles", "printed_start_page":169},
#     {"chapter_number":"14", "chapter_title":"Properties of Parallel Lines", "printed_start_page":174},
#     {"chapter_number":"15", "chapter_title":"Properties of Triangles", "printed_start_page":181},
#     {"chapter_number":"16", "chapter_title":"Congruence", "printed_start_page":195},
#     {"chapter_number":"17", "chapter_title":"Constructions", "printed_start_page":204},
#     {"chapter_number":"18", "chapter_title":"Reflection and Rotational Symmetry", "printed_start_page":214},
#     {"chapter_number":"19", "chapter_title":"Three-Dimensional Shapes", "printed_start_page":221},
#     {"chapter_number":"20", "chapter_title":"Mensuration", "printed_start_page":225},
#     {"chapter_number":"21", "chapter_title":"Collection and Organisation of Data (Mean, Median and Mode)", "printed_start_page":259},
#     {"chapter_number":"22", "chapter_title":"Bar Graphs", "printed_start_page":270},
#     {"chapter_number":"23", "chapter_title":"Probability", "printed_start_page":281},
#     {"chapter_number":"24", "chapter_title":"Activities", "printed_start_page":284},
#     {"chapter_number":"A", "chapter_title":"Answers", "printed_start_page":301, "chapter_type":"appendix"},
# ]

AUTO_CHAPTERS_JSON = Path(os.environ.get(
    'MATHS_RSAGGARWAL_CHAPTERS_JSON',
    OUTPUT_DIR / 'Maths_RSAgarwal_chapters.json',
))

if not AUTO_CHAPTERS_JSON.exists():
    raise FileNotFoundError(
        f'Auto-generated chapters file not found: {AUTO_CHAPTERS_JSON}\n'
        'Run Step 0 first:\n'
        'python app\\maths_rsaggarwal\\make_maths_rsaggarwal_step_0.py '
        '--pdf input\\Maths_RSAgarwal.pdf '
        '--output-json output\\Maths_RSAgarwal_chapters.json '
        '--output-py output\\Maths_RSAgarwal_chapters.py'
    )

_auto_chapter_config = json.loads(AUTO_CHAPTERS_JSON.read_text(encoding='utf-8'))
CHAPTERS = _auto_chapter_config['chapters']
PRINTED_OFFSET = int(_auto_chapter_config.get('printed_page_offset', PRINTED_OFFSET))

if not isinstance(CHAPTERS, list) or not CHAPTERS:
    raise ValueError(f'Invalid chapters list in {AUTO_CHAPTERS_JSON}')

ROMAN_LABELS = {1: None, 2: None, 3: None, 4: 'iii', 5: 'iv', 6: 'v', 7: None}
BAD_PDF_OCR_CHARS = ['न', 'प', 'वा', 'लि', 'नि', 'शि', 'छि', '॥', 'है', '', 'µ', 'Ã', '', 'Ê', '¯', '¾']
# Characters that are suspicious in an English/math OCR output. We do NOT mark ordinary math symbols as bad.
SUSPICIOUS_UNICODE_RE = re.compile(r'[\u0900-\u097F\uFFFD\u0080-\u009F]')
MATH_LINE_RE = re.compile(r'(?=.*[0-9a-zA-Z])(?=.*[=+\-−—*/×÷<>^|(){}\[\]√%])')
HEADING_RE = re.compile(r'^(EXAMPLE\s*\d+\.?|EXERCISE\s+[A-Z0-9]+|TEST\s+PAPER|OBJECTIVE QUESTIONS|Rule\s+\d+\.|SUMMARY|IMPORTANT RESULTS|Things to Remember)', re.IGNORECASE)


def clean_text(text: str) -> str:
    if not text:
        return ''
    text = text.replace('\x00', '')
    text = text.replace('\r\n', '\n').replace('\r', '\n')
    text = re.sub(r'[\x01-\x08\x0b\x0c\x0e-\x1f\x7f]', '', text)
    text = '\n'.join(line.rstrip() for line in text.split('\n'))
    text = re.sub(r'\n{4,}', '\n\n\n', text)
    return text.strip()


def normalize_math_ocr_text(text: str) -> str:
    """Light cleanup only. Avoid aggressive replacements that could change math meaning."""
    if not text:
        return ''
    text = clean_text(text)
    # Normalize common OCR dashes/minus signs to ASCII hyphen inside searchable text.
    text = text.replace('−', '-').replace('—', '-')
    # Common OCR quotes/dots cleanup.
    text = text.replace('“', '"').replace('”', '"').replace('‘', "'").replace('’', "'")
    # Join obvious broken page divider noise from Tesseract, but keep content lines.
    lines = []
    for line in text.split('\n'):
        stripped = line.strip()
        # Drop long fake separator lines caused by page border scanning.
        if len(stripped) > 25 and set(stripped) <= set('-_=~Ss. *'):
            continue
        lines.append(line.rstrip())
    return re.sub(r'\n{4,}', '\n\n\n', '\n'.join(lines)).strip()


def pdf_page_from_printed(printed_page: int) -> int:
    return printed_page + PRINTED_OFFSET


def printed_page_from_pdf(pdf_page: int) -> Optional[int]:
    return pdf_page - PRINTED_OFFSET if pdf_page >= 8 else None


def printed_label_from_pdf(pdf_page: int) -> Optional[str]:
    p = printed_page_from_pdf(pdf_page)
    if p is not None:
        return str(p)
    return ROMAN_LABELS.get(pdf_page)


def build_chapter_ranges(total_pdf_pages: int) -> List[dict]:
    items = []
    for i, ch in enumerate(CHAPTERS):
        start_printed = ch['printed_start_page']
        if i < len(CHAPTERS) - 1:
            end_printed = CHAPTERS[i + 1]['printed_start_page'] - 1
        else:
            end_printed = total_pdf_pages - PRINTED_OFFSET
        start_pdf = pdf_page_from_printed(start_printed)
        end_pdf = pdf_page_from_printed(end_printed)
        chapter_type = ch.get('chapter_type', 'chapter')
        items.append({
            **ch,
            'chapter_type': chapter_type,
            'start_page': start_pdf,
            'end_page': end_pdf,
            'printed_end_page': end_printed,
        })
    return items


def find_chapter_for_pdf_page(pdf_page: int, ranges: List[dict]) -> Optional[dict]:
    for ch in ranges:
        if ch['start_page'] <= pdf_page <= ch['end_page']:
            return ch
    return None


def classify_front_page(pdf_page: int, text: str) -> str:
    t = (text or '').lower()
    if not t:
        return 'blank'
    if pdf_page == 1:
        return 'cover'
    if pdf_page == 2:
        return 'title_page'
    if pdf_page == 3:
        return 'copyright_page'
    if 'preface' in t:
        return 'preface'
    if 'contents' in t and 'integers' in t:
        return 'toc'
    if 'covid' in t or 'pandemic' in t or 'content load' in t:
        return 'syllabus_reduction_note'
    return 'front_matter'


def ocr_quality_flags(text: str, selectable_text: str = '') -> Tuple[List[str], Dict[str, int]]:
    flags: List[str] = []
    suspicious_chars = SUSPICIOUS_UNICODE_RE.findall(text or '')
    bad_pdf_chars = sum((selectable_text or '').count(ch) for ch in BAD_PDF_OCR_CHARS)
    metrics = {
        'text_length': len(text or ''),
        'suspicious_unicode_count': len(suspicious_chars),
        'bad_pdf_ocr_char_count_in_selectable_layer': bad_pdf_chars,
        'math_line_count': len(extract_math_lines(text or '')),
    }
    if not (text or '').strip():
        flags.append('blank_or_no_ocr_text_detected')
    if len(suspicious_chars) > 0:
        flags.append('suspicious_unicode_in_ocr_text')
    if bad_pdf_chars > 0:
        flags.append('pdf_text_layer_had_corrupt_math_ocr_chars')
    if metrics['math_line_count'] > 8:
        flags.append('math_dense_page')
    # This book is scanned and math-heavy, so exact math should still be reviewed for high-stakes use.
    flags.append('rendered_page_ocr_used_for_math_text')
    return flags, metrics


def extract_math_lines(text: str) -> List[str]:
    out: List[str] = []
    for raw in (text or '').split('\n'):
        line = raw.strip()
        if len(line) < 3:
            continue
        if MATH_LINE_RE.search(line):
            out.append(line)
    return out[:80]  # prevent huge duplication in JSON


def extract_blocks(text: str) -> List[dict]:
    """Simple lightweight block markers for RAG metadata; not a full parser."""
    blocks: List[dict] = []
    current = None
    for line in (text or '').split('\n'):
        s = line.strip()
        if not s:
            continue
        m = HEADING_RE.match(s)
        if m:
            if current:
                current['text'] = '\n'.join(current['lines']).strip()
                del current['lines']
                blocks.append(current)
            title = m.group(1)
            block_type = 'example' if title.upper().startswith('EXAMPLE') else 'exercise' if title.upper().startswith('EXERCISE') else 'rule' if title.lower().startswith('rule') else 'section_marker'
            current = {'block_type': block_type, 'title': title, 'lines': [s]}
        elif current:
            current['lines'].append(s)
    if current:
        current['text'] = '\n'.join(current['lines']).strip()
        del current['lines']
        blocks.append(current)
    return blocks[:40]


def render_and_ocr_page(pdf_path: str, page_number: int) -> dict:
    """Worker: render a 1-based PDF page to image and OCR it with Tesseract."""
    OCR_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    # Prefer high-resolution OCR cache when available; fall back to full fast cache.
    high_cache_file = HIGH_RES_OCR_CACHE_DIR / f'page_{page_number:04d}_psm{TESSERACT_PSM}_scale2_0.txt'
    cache_file = OCR_CACHE_DIR / f'page_{page_number:04d}.txt'
    if high_cache_file.exists():
        ocr = high_cache_file.read_text(encoding='utf-8', errors='replace')
        return {'page_number': page_number, 'ocr_text_raw': ocr, 'from_cache': True, 'cache_profile': 'high_res_scale_2_0'}
    if cache_file.exists():
        ocr = cache_file.read_text(encoding='utf-8', errors='replace')
        return {'page_number': page_number, 'ocr_text_raw': ocr, 'from_cache': True, 'cache_profile': 'fast_scale_1_2'}

    doc = fitz.open(pdf_path)
    page = doc.load_page(page_number - 1)
    pix = page.get_pixmap(matrix=fitz.Matrix(RENDER_SCALE, RENDER_SCALE), alpha=False)
    with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp:
        tmp_path = tmp.name
    try:
        pix.save(tmp_path)
        env = os.environ.copy()
        env['OMP_THREAD_LIMIT'] = '1'
        cmd = [
            'tesseract', tmp_path, 'stdout',
            '--psm', TESSERACT_PSM,
            '-l', TESSERACT_LANG,
            '-c', 'preserve_interword_spaces=1',
        ]
        proc = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=False,
            env=env,
            timeout=60,
        )
        stdout_text = (proc.stdout or b'').decode('utf-8', errors='replace')
        stderr_text = (proc.stderr or b'').decode('utf-8', errors='replace')
        if proc.returncode != 0:
            ocr = ''
            err = stderr_text.strip()[:1000]
        else:
            ocr = stdout_text or ''
            err = ''
        cache_file.write_text(ocr, encoding='utf-8', errors='replace')
        return {'page_number': page_number, 'ocr_text_raw': ocr, 'from_cache': False, 'error': err}
    finally:
        try:
            os.remove(tmp_path)
        except OSError:
            pass


def format_page_block(page_record: dict) -> str:
    pp = page_record.get('printed_page_number')
    pp_label = pp if pp is not None else page_record.get('printed_page_label')
    return f"[PDF page {page_record['page_number']} / printed page {pp_label}]\n{page_record.get('text','').strip()}".strip()


# ----------------------------
# Chapter subsection detection
# ----------------------------
# A subsection is a page-level range inside a chapter.  For this book the safest
# automatic boundary is the exercise/activity heading.  The subsection starts at
# the page after the previous anchor page and ends on the current anchor page;
# the final subsection runs until the end of the chapter.  If the last exercise
# is an immediate/objective tail exercise, it is grouped with the previous anchor.
DEFAULT_SUBSECTIONS_JSON = 'Maths_RSAgarwal_static_subsection_ranges.json'


def _find_static_subsections_json() -> Path:
    """Locate the maintained day/subsection ranges JSON for this book."""
    env_path = os.environ.get('MATHS_RSAGGARWAL_SUBSECTIONS_JSON')
    candidates: List[Path] = []
    if env_path:
        candidates.append(Path(env_path))

    app_dir = Path(__file__).resolve().parent
    candidates.extend([
        PROJECT_ROOT / DEFAULT_SUBSECTIONS_JSON,
        app_dir / DEFAULT_SUBSECTIONS_JSON,
        app_dir / 'maths_rsaggarwal' / DEFAULT_SUBSECTIONS_JSON,
        OUTPUT_DIR / DEFAULT_SUBSECTIONS_JSON,
        PROJECT_ROOT / 'output' / 'maths_rsagarwal' / DEFAULT_SUBSECTIONS_JSON,
    ])

    for candidate in candidates:
        candidate = candidate if candidate.is_absolute() else PROJECT_ROOT / candidate
        if candidate.exists():
            return candidate

    checked = '\n'.join(f'- {c}' for c in candidates)
    raise FileNotFoundError(
        f'Maintained subsection/day ranges JSON not found: {DEFAULT_SUBSECTIONS_JSON}\n'
        'Place this standalone JSON in the project root, app/maths_rsaggarwal, or output/maths_rsagarwal, '
        'or set MATHS_RSAGGARWAL_SUBSECTIONS_JSON to its full path.\n'
        f'Checked:\n{checked}'
    )


def _normalize_static_marker(label: str, chapter_number: str) -> str:
    """Convert JSON exercise labels like '1A' into stable labels like 'Exercise 1A'."""
    label = str(label or '').strip()
    if not label:
        return ''
    if re.match(r'^activity\s+\d+', label, re.IGNORECASE):
        return 'Activity ' + re.search(r'\d+', label).group(0)
    if re.match(r'^exercise\s+', label, re.IGNORECASE):
        return re.sub(r'\s+', ' ', label).strip().title().replace('exercise', 'Exercise')
    if re.match(r'^\d+[A-Za-z]?$', label):
        return f'Exercise {label.upper()}'
    return label


def _load_static_subsection_config(path: Path) -> dict:
    data = json.loads(path.read_text(encoding='utf-8'))
    chapters = data.get('chapters')
    if not isinstance(chapters, list) or not chapters:
        raise ValueError(f'Invalid subsection JSON. Expected non-empty chapters array: {path}')
    return data


def _build_known_subsection_plan_from_json(config: dict) -> Dict[str, List[dict]]:
    """Build the old internal plan shape from the standalone JSON file."""
    plan: Dict[str, List[dict]] = {}
    for chapter in config.get('chapters') or []:
        chapter_number = str(chapter.get('chapter_number') or chapter.get('sequence') or '').strip()
        if not chapter_number:
            continue
        day_rows: List[dict] = []
        for idx, day in enumerate(chapter.get('days') or [], start=1):
            day_no = int(day.get('day') or idx)
            exercises = day.get('exercises') or []
            if isinstance(exercises, str):
                exercises = [exercises]
            included = [_normalize_static_marker(x, chapter_number) for x in exercises if str(x).strip()]
            included = [x for x in included if x]
            if not included:
                if str(chapter.get('chapter_name', '')).strip().lower() == 'activities':
                    included = [f'Activity {day_no}']
                else:
                    included = [f'Exercise {chapter_number}']
            anchor = included[0]
            notes = []
            if day.get('includes'):
                notes.append(str(day.get('includes')))
            if day.get('note'):
                notes.append(str(day.get('note')))
            notes.append('Subsection/day range loaded from standalone Maths_RSAgarwal_static_subsection_ranges.json; no runtime exercise detection used.')

            day_rows.append({
                'day': day_no,
                'day_title': day.get('day_title') or f'Day {day_no}',
                'day_type': day.get('day_type'),
                'anchor_marker': anchor,
                'anchor_pdf_page': day.get('end_pdf_page'),
                'anchor_printed_page': day.get('end_book_page'),
                'included_exercises_or_activities': included,
                'raw_exercises': exercises,
                'includes_text': day.get('includes'),
                'start_page': int(day['start_pdf_page']),
                'end_page': int(day['end_pdf_page']),
                'printed_start_page': int(day['start_book_page']),
                'printed_end_page': int(day['end_book_page']),
                'range_source': day.get('range_source') or config.get('subsection_policy') or 'maintained_static_json',
                'boundary_overlap_with_previous_day': bool(day.get('boundary_overlap_with_previous_day')),
                'notes': notes,
            })
        if day_rows:
            plan[chapter_number] = day_rows
    return plan


STATIC_SUBSECTIONS_JSON = _find_static_subsections_json()
STATIC_SUBSECTION_CONFIG = _load_static_subsection_config(STATIC_SUBSECTIONS_JSON)
KNOWN_SUBSECTION_PLAN_BY_CHAPTER = _build_known_subsection_plan_from_json(STATIC_SUBSECTION_CONFIG)


TRAILING_EXERCISE_GROUPS_BY_CHAPTER = {
    '1': {'Exercise 1D'},
    '2': {'Exercise 2D'},
    '3': {'Exercise 3E'},
    '4': {'Exercise 4G'},
    '5': {'Exercise 5C'},
    '7': {'Exercise 7C'},
    '8': {'Exercise 8C'},
    '9': {'Exercise 9C'},
    '10': {'Exercise 10C'},
    '11': {'Exercise 11B'},
    '12': {'Exercise 12B'},
    '17': {'Exercise 17C'},
    '20': {'Exercise 20G'},
}

EXERCISE_TOKEN_RE = re.compile(r'\bEXERCISE\s+([0-9A-Za-z¢©]{1,5})', re.IGNORECASE)
ACTIVITY_TOKEN_RE = re.compile(r'\bACTIVITY\s+([0-9]{1,2})', re.IGNORECASE)
OCR_LETTER_FIXES = {
    '¢': 'C', '©': 'C', '0': 'O',
    # OCR sometimes reads B as 8, especially in Exercise 1B-style headings.
    '8': 'B',
}


def _normalize_marker_token(token: str) -> str:
    token = (token or '').strip().upper()
    token = token.replace('¢', 'C').replace('©', 'C')
    token = token.replace('I', '1').replace('L', '1')
    token = token.replace('O', '0')
    return token


def _normalize_exercise_marker(raw_token: str, chapter_number: str) -> str | None:
    """Return canonical labels like 'Exercise 1A' or 'Exercise 13'."""
    if not chapter_number or not str(chapter_number).isdigit():
        return None
    chapter_number = str(chapter_number)
    token = _normalize_marker_token(raw_token)
    if not token:
        return None

    # Normal case: token starts with the chapter number, e.g. 20F.
    if token.startswith(chapter_number):
        suffix = token[len(chapter_number):]
        suffix = ''.join(OCR_LETTER_FIXES.get(ch, ch) for ch in suffix)
        suffix = re.sub(r'[^A-Z]', '', suffix)
        return f'Exercise {chapter_number}{suffix}' if suffix else f'Exercise {chapter_number}'

    # Common OCR case for chapter 1: '1B' can be read as just '8'.
    if len(token) == 1 and chapter_number == '1' and token in OCR_LETTER_FIXES:
        fixed = OCR_LETTER_FIXES[token]
        if fixed.isalpha():
            return f'Exercise {chapter_number}{fixed}'

    # If the token is only a letter, attach it to the current chapter.
    if len(token) == 1 and token.isalpha():
        return f'Exercise {chapter_number}{token}'

    return None


def detect_subsection_markers(chapter: dict, pages: List[dict]) -> List[dict]:
    """Detect exercise/activity anchors inside a chapter from OCR page text."""
    chapter_number = str(chapter.get('chapter_number'))
    chapter_title = chapter.get('chapter_title') or ''
    markers: List[dict] = []
    seen = set()

    is_activity_chapter = chapter_number == '24' or chapter_title.lower() == 'activities'
    for page in pages:
        text = page.get('text') or page.get('text_plain') or ''
        if not text:
            continue

        if is_activity_chapter:
            for m in ACTIVITY_TOKEN_RE.finditer(text):
                marker = f"Activity {int(m.group(1))}"
                if marker in seen:
                    continue
                seen.add(marker)
                markers.append({
                    'marker': marker,
                    'kind': 'activity',
                    'page_number': page.get('page_number'),
                    'printed_page_number': page.get('printed_page_number'),
                    'order': m.start(),
                })
            continue

        for m in EXERCISE_TOKEN_RE.finditer(text):
            marker = _normalize_exercise_marker(m.group(1), chapter_number)
            if not marker or marker in seen:
                continue
            seen.add(marker)
            markers.append({
                'marker': marker,
                'kind': 'exercise',
                'page_number': page.get('page_number'),
                'printed_page_number': page.get('printed_page_number'),
                'order': m.start(),
            })

    markers.sort(key=lambda x: (int(x.get('page_number') or 0), int(x.get('order') or 0), x.get('marker') or ''))
    return markers


def group_subsection_markers(chapter: dict, markers: List[dict]) -> List[dict]:
    """Group immediate/objective tail exercises with the previous subsection."""
    chapter_number = str(chapter.get('chapter_number'))
    trailing_group = TRAILING_EXERCISE_GROUPS_BY_CHAPTER.get(chapter_number, set())
    groups: List[dict] = []
    for marker in markers:
        label = marker['marker']
        if label in trailing_group and groups:
            groups[-1]['included_markers'].append(label)
            groups[-1]['included_marker_details'].append(marker)
            groups[-1]['notes'].append('Objective/immediate exercise grouped with the preceding concept subsection.')
            continue
        groups.append({
            'anchor': marker,
            'included_markers': [label],
            'included_marker_details': [marker],
            'notes': [],
        })
    return groups


def build_subsection_record(chapter: dict, group: dict, idx: int, start_page: int, end_page: int, subsection_pages: List[dict]) -> dict:
    page_numbers = [p.get('page_number') for p in subsection_pages if p.get('page_number') is not None]
    printed_page_numbers = [p.get('printed_page_number') for p in subsection_pages if p.get('printed_page_number') is not None]
    subsection_text = '\n\n'.join(format_page_block(p) for p in subsection_pages if (p.get('text') or '').strip())
    combined_math_lines: List[str] = []
    for p in subsection_pages:
        combined_math_lines.extend(p.get('math_lines', [])[:20])

    anchor = group['anchor']
    included = group.get('included_markers') or [anchor.get('marker')]
    start_printed = printed_page_numbers[0] if printed_page_numbers else printed_page_from_pdf(start_page)
    end_printed = printed_page_numbers[-1] if printed_page_numbers else printed_page_from_pdf(end_page)
    notes = ['Page-level range; if an exercise/activity heading starts mid-page, the whole PDF page is assigned to this subsection.']
    notes.extend(group.get('notes') or [])

    return {
        'section_number': chapter.get('chapter_number'),
        'section_title': chapter.get('chapter_title'),
        'unit_number': None,
        'unit_title': None,
        'chapter_type': chapter.get('chapter_type'),
        'chapter_number': chapter.get('chapter_number'),
        'chapter_title': chapter.get('chapter_title'),
        'subsection_number': f"{chapter.get('chapter_number')}.{idx}",
        'subsection_title': f"Before/through {anchor.get('marker')}",
        'anchor_marker': anchor.get('marker'),
        'anchor_pdf_page': anchor.get('page_number'),
        'anchor_printed_page': anchor.get('printed_page_number'),
        'included_exercises_or_activities': included,
        'includes': included,
        'start_page': start_page,
        'end_page': end_page,
        'start_pdf_page': start_page,
        'end_pdf_page': end_page,
        'printed_start_page': start_printed,
        'printed_end_page': end_printed,
        'start_printed_page': start_printed,
        'end_printed_page': end_printed,
        'pdf_pages': {'start': start_page, 'end': end_page},
        'printed_pages': {'start': start_printed, 'end': end_printed},
        'page_count': len(page_numbers),
        'subsection_text': subsection_text,
        'subsection_text_plain': subsection_text,
        'text_plain': subsection_text,
        'subsection_math_lines': combined_math_lines[:300],
        'math_lines': combined_math_lines[:300],
        'physical_start_page': start_page,
        'physical_end_page': end_page,
        'physical_printed_start_page': start_printed,
        'physical_printed_end_page': end_printed,
        'physical_page_count': max(0, end_page - start_page + 1),
        'page_numbers': page_numbers,
        'printed_page_numbers': printed_page_numbers,
        'excluded_related_pages': [],
        'text_sources': ['rendered_page_tesseract_ocr'],
        'quality_flags': sorted({flag for p in subsection_pages for flag in p.get('quality_flags', [])}),
        'include_in_embeddings': bool(subsection_text.strip()),
        'notes': notes,
    }



def build_known_subsections_for_chapter(chapter: dict, indexed_pages: List[dict]) -> List[dict]:
    """Use the maintained standalone day/subsection JSON for R. S. Aggarwal Class 7."""
    plan = KNOWN_SUBSECTION_PLAN_BY_CHAPTER.get(str(chapter.get('chapter_number')))
    if not plan or not indexed_pages:
        return []

    page_by_number = {int(p.get('page_number')): p for p in indexed_pages if p.get('page_number') is not None}
    chapter_start = min(page_by_number) if page_by_number else None
    chapter_end = max(page_by_number) if page_by_number else None
    out: List[dict] = []

    for idx, item in enumerate(plan, start=1):
        start_page = int(item['start_page'])
        end_page = int(item['end_page'])
        if chapter_start is not None:
            start_page = max(start_page, chapter_start)
        if chapter_end is not None:
            end_page = min(end_page, chapter_end)
        if end_page < start_page:
            # Keep a clear placeholder instead of silently creating a bad range.
            start_page = int(item['start_page'])
            end_page = int(item['end_page'])
            subsection_pages = []
        else:
            subsection_pages = [page_by_number[p] for p in range(start_page, end_page + 1) if p in page_by_number]

        group = {
            'anchor': {
                'marker': item['anchor_marker'],
                'page_number': item.get('anchor_pdf_page') or end_page,
                'printed_page_number': item.get('anchor_printed_page') or item.get('printed_end_page'),
            },
            'included_markers': list(item.get('included_exercises_or_activities') or []),
            'included_marker_details': [],
            'notes': list(item.get('notes') or []),
        }
        rec = build_subsection_record(chapter, group, idx, start_page, end_page, subsection_pages)

        day_no = int(item.get('day') or idx)
        rec['day'] = day_no
        rec['day_title'] = item.get('day_title') or f'Day {day_no}'
        rec['day_type'] = item.get('day_type')
        rec['subsection_number'] = f"{chapter.get('chapter_number')}.{day_no}"
        rec['subsection_title'] = rec['day_title']
        rec['anchor_marker'] = item.get('anchor_marker')
        rec['anchor_pdf_page'] = item.get('anchor_pdf_page') or end_page
        rec['anchor_printed_page'] = item.get('anchor_printed_page') or item.get('printed_end_page')
        rec['included_exercises_or_activities'] = list(item.get('included_exercises_or_activities') or [])
        rec['includes'] = list(item.get('included_exercises_or_activities') or [])
        rec['exercises'] = list(item.get('raw_exercises') or [])
        rec['day_includes'] = item.get('includes_text')
        rec['range_source'] = item.get('range_source')
        rec['range_source_file'] = str(STATIC_SUBSECTIONS_JSON)
        rec['subsection_policy'] = STATIC_SUBSECTION_CONFIG.get('subsection_policy') or 'maintained_static_day_ranges_read_from_json_file'
        rec['day_split_policy'] = STATIC_SUBSECTION_CONFIG.get('day_split_policy')
        rec['boundary_overlap_with_previous_day'] = bool(item.get('boundary_overlap_with_previous_day'))

        # Prefer audited printed page numbers from the standalone JSON.
        rec['printed_start_page'] = item.get('printed_start_page')
        rec['printed_end_page'] = item.get('printed_end_page')
        rec['start_printed_page'] = item.get('printed_start_page')
        rec['end_printed_page'] = item.get('printed_end_page')
        rec['printed_pages'] = {'start': item.get('printed_start_page'), 'end': item.get('printed_end_page')}
        rec['physical_printed_start_page'] = item.get('printed_start_page')
        rec['physical_printed_end_page'] = item.get('printed_end_page')
        rec['notes'] = list(item.get('notes') or rec.get('notes') or [])
        out.append(rec)
    return out


def build_subsections_for_chapter(chapter: dict, indexed_pages: List[dict]) -> List[dict]:
    """Build subsection/day array from the standalone JSON file only."""
    if not indexed_pages or chapter.get('chapter_type') == 'appendix':
        return []

    known_subsections = build_known_subsections_for_chapter(chapter, indexed_pages)
    if known_subsections:
        return known_subsections

    # Do not dynamically infer Exercise/Activity boundaries here. The maintained
    # JSON is now the source of truth. If a chapter is missing from that JSON,
    # keep one safe chapter-level subsection and make the issue visible.
    start_page = int(indexed_pages[0].get('page_number'))
    end_page = int(indexed_pages[-1].get('page_number'))
    fallback_group = {
        'anchor': {
            'marker': 'Chapter body',
            'page_number': start_page,
            'printed_page_number': indexed_pages[0].get('printed_page_number'),
        },
        'included_markers': [],
        'included_marker_details': [],
        'notes': [
            'No maintained static day range was found for this chapter in the standalone JSON; dynamic day detection was intentionally not used.'
        ],
    }
    rec = build_subsection_record(chapter, fallback_group, 1, start_page, end_page, indexed_pages)
    rec['range_source'] = 'missing_from_static_subsections_json'
    rec['range_source_file'] = str(STATIC_SUBSECTIONS_JSON)
    rec['subsection_policy'] = STATIC_SUBSECTION_CONFIG.get('subsection_policy') or 'maintained_static_day_ranges_read_from_json_file'
    rec['quality_flags'] = sorted(set(rec.get('quality_flags', [])) | {'missing_static_day_range'})
    return [rec]


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OCR_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    HIGH_RES_OCR_CACHE_DIR.mkdir(parents=True, exist_ok=True)

    if not PDF_PATH.exists():
        raise FileNotFoundError(PDF_PATH)
    if not AUTO_CHAPTERS_JSON.exists():
        raise FileNotFoundError(AUTO_CHAPTERS_JSON)

    doc = fitz.open(str(PDF_PATH))
    total_pdf_pages = doc.page_count
    ranges = build_chapter_ranges(total_pdf_pages)

    print(f'PDF pages: {total_pdf_pages}', flush=True)
    print(f'Running rendered-page OCR with {MAX_WORKERS} workers, scale={RENDER_SCALE}, psm={TESSERACT_PSM}', flush=True)

    # 1. Get PDF text layer only for comparison/quality audit.
    selectable_by_page: Dict[int, str] = {}
    for i in range(total_pdf_pages):
        page_number = i + 1
        selectable_by_page[page_number] = clean_text(doc.load_page(i).get_text('text') or '')

    # 2. OCR every page from rendered image. This is the main text used in final JSON.
    # Sequential loop is intentionally used here: it is more stable for large scanned PDFs
    # than spawning many workers that each open the same 120MB PDF.
    ocr_by_page: Dict[int, dict] = {}
    for p in range(1, total_pdf_pages + 1):
        try:
            result = render_and_ocr_page(str(PDF_PATH), p)
        except Exception as exc:
            result = {'page_number': p, 'ocr_text_raw': '', 'from_cache': False, 'error': repr(exc)}
        ocr_by_page[p] = result
        if p % 25 == 0 or p == total_pdf_pages:
            print(f'OCR completed {p}/{total_pdf_pages}', flush=True)

    raw_pages = []
    for pdf_page in range(1, total_pdf_pages + 1):
        selectable_text = selectable_by_page.get(pdf_page, '')
        raw_ocr = ocr_by_page.get(pdf_page, {}).get('ocr_text_raw', '')
        ocr_text = normalize_math_ocr_text(raw_ocr)
        flags, metrics = ocr_quality_flags(ocr_text, selectable_text)
        text_sources = ['rendered_page_tesseract_ocr']
        if selectable_text:
            text_sources.append('pdf_text_layer_reference_only')
        raw_pages.append({
            'page_number': pdf_page,
            'printed_page_number': printed_page_from_pdf(pdf_page),
            'printed_page_label': printed_label_from_pdf(pdf_page),
            'text': ocr_text,
            'text_plain': ocr_text,
            'math_lines': extract_math_lines(ocr_text),
            'extracted_blocks': extract_blocks(ocr_text),
            'selectable_text': selectable_text,
            'ocr_text': ocr_text,
            'ocr_engine': 'tesseract',
            'ocr_profile': {
                'render_scale': 'mixed: high_res_scale_2_0_when_cached_else_fast_scale_1_2',
                'estimated_dpi': 'mixed: 144 for high-res cached pages, 86 for fallback pages',
                'language': TESSERACT_LANG,
                'psm': TESSERACT_PSM,
                'preserve_interword_spaces': True,
            },
            'text_sources': text_sources,
            'quality_flags': flags,
            'quality_metrics': metrics,
        })

    page_extractions = []
    chapter_pages = {ch['chapter_number']: [] for ch in ranges}
    front_matter_pages = []

    for page in raw_pages:
        pdf_page = page['page_number']
        assigned = find_chapter_for_pdf_page(pdf_page, ranges)
        if assigned:
            content_type = 'answer_key' if assigned['chapter_type'] == 'appendix' else 'lesson_body'
            page_rec = {
                **page,
                'chapter_type': assigned['chapter_type'],
                'chapter_number': assigned['chapter_number'],
                'chapter_title': assigned['chapter_title'],
                'unit_number': None,
                'unit_title': None,
                'section_number': assigned['chapter_number'],
                'section_title': assigned['chapter_title'],
                'content_type': content_type,
                'assignment_status': 'assigned_to_chapter' if assigned['chapter_type'] == 'chapter' else 'assigned_to_appendix',
                'include_in_lesson_text': True,
                'include_in_embeddings': bool(page.get('text')),
                'linked_section_title': None,
                'linked_section_number': None,
                'unit_level_title': None,
            }
            chapter_pages[assigned['chapter_number']].append(page_rec)
        else:
            ctype = classify_front_page(pdf_page, page['text'])
            page_rec = {
                **page,
                'chapter_type': None,
                'chapter_number': None,
                'chapter_title': None,
                'unit_number': None,
                'unit_title': None,
                'section_number': None,
                'section_title': None,
                'content_type': ctype,
                'assignment_status': 'front_matter' if ctype != 'blank' else 'blank',
                'include_in_lesson_text': False,
                'include_in_embeddings': False,
                'linked_section_title': None,
                'linked_section_number': None,
                'unit_level_title': None,
            }
            front_matter_pages.append(page_rec)
        page_extractions.append(page_rec)

    chapters_out = []
    section_index = []
    for ch in ranges:
        pages = chapter_pages[ch['chapter_number']]
        indexed_pages = [p for p in pages if p.get('include_in_lesson_text')]
        lesson_text = '\n\n'.join(format_page_block(p) for p in indexed_pages if p.get('text'))
        text_len = len(lesson_text)
        page_numbers = [p['page_number'] for p in indexed_pages]
        printed_page_numbers = [p['printed_page_number'] for p in indexed_pages if p.get('printed_page_number') is not None]
        combined_math_lines = []
        for p in indexed_pages:
            combined_math_lines.extend(p.get('math_lines', [])[:20])
        lesson = {
            'section_number': ch['chapter_number'],
            'section_title': ch['chapter_title'],
            'unit_number': None,
            'unit_title': None,
            'chapter_type': ch['chapter_type'],
            'chapter_number': ch['chapter_number'],
            'chapter_title': ch['chapter_title'],
            'start_page': page_numbers[0] if page_numbers else ch['start_page'],
            'end_page': page_numbers[-1] if page_numbers else ch['end_page'],
            'printed_start_page': printed_page_numbers[0] if printed_page_numbers else ch['printed_start_page'],
            'printed_end_page': printed_page_numbers[-1] if printed_page_numbers else ch['printed_end_page'],
            'page_count': len(page_numbers),
            'lesson_text': lesson_text,
            'text_plain': lesson_text,
            'math_lines': combined_math_lines[:300],
            'physical_start_page': ch['start_page'],
            'physical_end_page': ch['end_page'],
            'physical_printed_start_page': ch['printed_start_page'],
            'physical_printed_end_page': ch['printed_end_page'],
            'physical_page_count': ch['end_page'] - ch['start_page'] + 1,
            'page_numbers': page_numbers,
            'printed_page_numbers': printed_page_numbers,
            'excluded_related_pages': [],
            'text_sources': ['rendered_page_tesseract_ocr'],
            'quality_flags': sorted({flag for p in indexed_pages for flag in p.get('quality_flags', [])}),
            'include_in_embeddings': True,
        }
        subsections = build_subsections_for_chapter(ch, indexed_pages)

        chapter_obj = {
            'chapter_type': ch['chapter_type'],
            'chapter_number': ch['chapter_number'],
            'chapter_title': ch['chapter_title'],
            'unit_number': None,
            'unit_title': None,
            'start_page': ch['start_page'],
            'end_page': ch['end_page'],
            'printed_start_page': ch['printed_start_page'],
            'printed_end_page': ch['printed_end_page'],
            'lessons': [lesson],
            'subsections': subsections,
        }
        chapters_out.append(chapter_obj)
        section_index.append({
            'section_number': ch['chapter_number'],
            'section_title': ch['chapter_title'],
            'unit_number': None,
            'unit_title': None,
            'chapter_type': ch['chapter_type'],
            'chapter_number': ch['chapter_number'],
            'chapter_title': ch['chapter_title'],
            'start_page': lesson['start_page'],
            'end_page': lesson['end_page'],
            'printed_start_page': lesson['printed_start_page'],
            'printed_end_page': lesson['printed_end_page'],
            'page_count': lesson['page_count'],
            'text_length_chars': text_len,
            'physical_start_page': lesson['physical_start_page'],
            'physical_end_page': lesson['physical_end_page'],
            'physical_printed_start_page': lesson['physical_printed_start_page'],
            'physical_printed_end_page': lesson['physical_printed_end_page'],
            'physical_page_count': lesson['physical_page_count'],
            'indexed_page_count': lesson['page_count'],
            'indexed_page_numbers': lesson['page_numbers'],
            'indexed_printed_page_numbers': lesson['printed_page_numbers'],
            'excluded_related_pages': [],
            'text_sources': lesson['text_sources'],
            'quality_flags': lesson['quality_flags'],
        })

    total_text_chars = sum(len(p.get('text') or '') for p in page_extractions)
    empty_pages = [p['page_number'] for p in page_extractions if not (p.get('text') or '').strip()]
    suspicious_pages = [
        p['page_number'] for p in page_extractions
        if p.get('quality_metrics', {}).get('suspicious_unicode_count', 0) > 0
    ]
    pdf_layer_bad_pages = [
        p['page_number'] for p in page_extractions
        if p.get('quality_metrics', {}).get('bad_pdf_ocr_char_count_in_selectable_layer', 0) > 0
    ]

    data = {
        'metadata': {
            'school_name': 'Mother Miracle School',
            'class_name': 'Class-7',
            'grade': 'Class-7',
            'board': 'CBSE',
            'medium': 'English',
            'publisher': 'Bharati Bhawan',
            'copyright_status': 'copyrighted',
            'source_file': PDF_PATH.name,
        },
        'extraction': {
            'book_title': 'Mathematics for Class 7',
            'subject': 'Maths',
            'language': 'English',
            'content_profile': 'math_textbook',
            'structure_type': 'chapters',
            'author': 'R S Aggarwal',
            'total_pdf_pages': total_pdf_pages,
            'content_start_page': 8,
            'content_end_page': 307,
            'answers_start_page': 308,
            'answers_end_page': total_pdf_pages,
            'printed_page_offset': PRINTED_OFFSET,
            'subsection_policy': STATIC_SUBSECTION_CONFIG.get('subsection_policy') or 'maintained_static_day_ranges_read_from_json_file',
            'day_split_policy': STATIC_SUBSECTION_CONFIG.get('day_split_policy'),
            'subsections_json_source': str(STATIC_SUBSECTIONS_JSON),
            'math_ocr_profile': {
                'method': 'rendered_page_ocr_before_embedding_mixed_resolution_cache',
                'engine': 'tesseract',
                'language': TESSERACT_LANG,
                'psm': TESSERACT_PSM,
                'render_scale': 'mixed: high_res_scale_2_0_when_cached_else_fast_scale_1_2',
                'estimated_dpi': 'mixed: 144 for high-res cached pages, 86 for fallback pages',
                'preserve_interword_spaces': True,
                'text_layer_policy': 'selectable PDF text kept only for audit; final text uses rendered-page OCR',
            },
            'notes': [
                'This JSON regenerates page text from rendered page images instead of relying on the corrupt selectable PDF/OCR layer.',
                'The chapter ranges come from the book contents page. Printed page 1 maps to PDF page 8.',
                'Subsection/day ranges are loaded from the maintained standalone Maths_RSAgarwal_static_subsection_ranges.json file; runtime exercise/day detection is not used.',
                'For math RAG, use page_extractions.text or lesson_text from this file, not selectable_text.',
                'Tesseract OCR is much cleaner than the embedded/selectable text for this scanned PDF, but stacked fractions, powers, and dense answer-key layouts can still require manual QA or Mathpix/LLM-vision for perfect LaTeX.',
            ],
            'section_index': section_index,
            'chapters': chapters_out,
            'front_matter_pages': [
                {
                    'page_number': p['page_number'],
                    'printed_page_number': p['printed_page_number'],
                    'printed_page_label': p['printed_page_label'],
                    'content_type': p['content_type'],
                    'text': p['text'],
                    'selectable_text': p['selectable_text'],
                    'math_lines': p.get('math_lines', []),
                    'text_sources': p['text_sources'],
                    'quality_flags': p['quality_flags'],
                    'quality_metrics': p['quality_metrics'],
                }
                for p in front_matter_pages
            ],
            'page_extractions': page_extractions,
            'transcripts': [],
            'unit_level_pages': [],
            'detected_transcript_pages': [],
            'quality_summary': {
                'total_pages': total_pdf_pages,
                'assigned_content_pages': sum(1 for p in page_extractions if p.get('include_in_lesson_text')),
                'total_subsections': sum(len(ch.get('subsections', [])) for ch in chapters_out),
                'subsections_json_source': str(STATIC_SUBSECTIONS_JSON),
                'subsection_plan_chapter_count': len(KNOWN_SUBSECTION_PLAN_BY_CHAPTER),
                'front_matter_page_count': len(front_matter_pages),
                'empty_or_no_text_pages': empty_pages,
                'pages_with_suspicious_unicode_in_final_ocr_text': suspicious_pages,
                'pages_where_selectable_pdf_layer_was_corrupt': pdf_layer_bad_pages,
                'total_extracted_text_chars': total_text_chars,
                'recommended_embedding_text_field': 'text',
                'recommended_embedding_filter': 'include_in_embeddings == true',
                'ocr_warning': 'Rendered-page OCR is cleaner than the PDF text layer, but this is not perfect symbolic math LaTeX extraction. Use Mathpix/LLM vision for exact formula reconstruction if exact equations are critical.',
            },
            'generated_at_utc': datetime.now(timezone.utc).isoformat(),
        },
    }

    OUTPUT_JSON.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')

    errors: List[str] = []
    warnings: List[str] = []
    covered = []
    for ch in chapters_out:
        if ch['start_page'] > ch['end_page']:
            errors.append(f"Chapter {ch['chapter_number']} has invalid PDF range {ch['start_page']}-{ch['end_page']}")
        covered.extend(range(ch['start_page'], ch['end_page'] + 1))
        lesson = ch['lessons'][0]
        if lesson['page_count'] != len(lesson['page_numbers']):
            errors.append(f"Chapter {ch['chapter_number']} page_count mismatch")
        if lesson['physical_page_count'] != ch['end_page'] - ch['start_page'] + 1:
            errors.append(f"Chapter {ch['chapter_number']} physical_page_count mismatch")
        if not lesson['lesson_text'].strip():
            warnings.append(f"Chapter {ch['chapter_number']} has empty lesson_text")
    expected = list(range(8, total_pdf_pages + 1))
    missing = sorted(set(expected) - set(covered))
    extra = sorted(set(covered) - set(expected))
    if missing:
        errors.append(f"Missing content/answer pages from chapter mapping: {missing[:20]}{'...' if len(missing)>20 else ''}")
    if extra:
        errors.append(f"Chapter mapping contains pages outside expected content range: {extra[:20]}{'...' if len(extra)>20 else ''}")
    dupes = sorted({p for p in covered if covered.count(p) > 1})
    if dupes:
        errors.append(f"Duplicate chapter page assignments: {dupes[:20]}{'...' if len(dupes)>20 else ''}")
    if empty_pages:
        warnings.append(f"Pages with no final OCR text: {empty_pages}")
    if suspicious_pages:
        warnings.append(f"Pages with suspicious Unicode in final OCR text: {suspicious_pages[:50]}{'...' if len(suspicious_pages)>50 else ''}")
    if pdf_layer_bad_pages:
        warnings.append(f"Selectable PDF layer had corrupt/non-English OCR artifacts on {len(pdf_layer_bad_pages)} pages; final JSON uses rendered-page OCR instead.")
    warnings.append('Rendered-page OCR improved major corruption such as Hindi glyphs in equations, but stacked fractions/exponents may still need Mathpix/LLM-vision/manual QA for exact LaTeX.')

    report_lines = [
        'Maths_RSAgarwal math-aware OCR extraction validation report',
        f"Generated UTC: {data['extraction']['generated_at_utc']}",
        f'Source PDF: {PDF_PATH.name}',
        f'Total PDF pages: {total_pdf_pages}',
        f'Chapters/sections generated: {len(section_index)}',
        f'Subsections generated: {sum(len(ch.get("subsections", [])) for ch in chapters_out)}',
        f'OCR method: rendered page image -> Tesseract lang={TESSERACT_LANG}, psm={TESSERACT_PSM}, scale={RENDER_SCALE}',
        f'Page mapping: printed page = PDF page - {PRINTED_OFFSET} for PDF pages >= 8',
        f'Pages where old selectable layer had corrupt OCR artifacts: {len(pdf_layer_bad_pages)}',
        f'Pages with suspicious unicode in final OCR text: {len(suspicious_pages)}',
        '',
        'Errors:',
        'None' if not errors else '\n'.join(f'- {e}' for e in errors),
        '',
        'Warnings:',
        'None' if not warnings else '\n'.join(f'- {w}' for w in warnings),
        '',
        'Sample improvement checks:',
    ]
    sample_pages = [8, 10, 14, 23, 91, 308]
    for p in sample_pages:
        page = next(x for x in page_extractions if x['page_number'] == p)
        old_bad = page['quality_metrics']['bad_pdf_ocr_char_count_in_selectable_layer']
        new_bad = page['quality_metrics']['suspicious_unicode_count']
        snippet = ' '.join(page['text'].split())[:500]
        report_lines.append(f'- PDF page {p}: old selectable bad-char count={old_bad}, final OCR suspicious unicode count={new_bad}')
        report_lines.append(f'  OCR snippet: {snippet}')
    report_lines.extend(['', 'Section ranges:'])
    for sec in section_index:
        report_lines.append(
            f"- {sec['section_number']}. {sec['section_title']}: PDF {sec['start_page']}-{sec['end_page']} / printed {sec['printed_start_page']}-{sec['printed_end_page']} / pages {sec['page_count']} / chars {sec['text_length_chars']}"
        )
    VALIDATION_REPORT.write_text('\n'.join(report_lines), encoding='utf-8')

    print(f'Wrote {OUTPUT_JSON}', flush=True)
    print(f'Wrote {VALIDATION_REPORT}', flush=True)
    print(f'Errors: {len(errors)} Warnings: {len(warnings)}', flush=True)


if __name__ == '__main__':
    main()
